local K = unpack(KkthnxUI)
local Module = K:NewModule("Automation")

function Module:OnEnable()
	self:CreateAutoAcceptSummon()
	self:CreateAutoBadBuffs()
	self:CreateAutoBestReward()
	self:CreateAutoDeclineDuels()
	self:CreateAutoDismount()
	self:CreateAutoInvite()
	self:CreateAutoOpenItems()
	self:CreateAutoRelease()
	self:CreateAutoResurrect()
	self:CreateAutoTabBinder()
	self:CreateAutoWhisperInvite()
	self:CreateCounterSpitters()
	self:CreateAutoRefillAmmo()
	self:CreateSkipCinematic()
end